import { Product } from '../types/product';
import { User } from '../types/user';
import { Order } from '../types/order';

/**
 * Mock data generators for products, users, and orders
 */

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Donuts Coloridos',
    description: 'Deliciosos donuts vitrificados com cobertura colorida e granulado',
    price: 18.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_colorful-donuts-4969.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Donuts Gourmet',
    description: 'Variedade de donuts artesanais com coberturas premium',
    price: 22.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_colorful-donuts-4970.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Waffles com Framboesas',
    description: 'Waffles quentinhos cobertos com framboesas frescas e calda',
    price: 25.90,
    category: 'Café da Manhã',
    imageUrl: '/kaboompics_breakfast-waffles-with-fresh-raspberries-3260.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Cheesecake de Frutas Vermelhas',
    description: 'Cheesecake cremoso com blueberries e framboesas frescas',
    price: 28.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_cheesecake-with-blueberries-and-raspberries-5599.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Cookies Chips de Chocolate',
    description: 'Cookies caseiros com generosas lascas de chocolate',
    price: 15.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_chocolate-chip-cookies-in-a-jar-20135.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Bolo de Matcha',
    description: 'Bolo caseiro de matcha com textura fofa e sabor único',
    price: 32.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_delicious-homemade-matcha-cake-on-a-wooden-board-3393.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: 'Milkshake de Frutas',
    description: 'Milkshake fresco e saudável com frutas da estação',
    price: 16.90,
    category: 'Bebida',
    imageUrl: '/kaboompics_fresh-and-healthy-fruit-milkshake-with-a-straw-4365.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'Brownie de Feijão Vermelho',
    description: 'Brownie sem glúten com pasta de amendoim, feito com feijão vermelho',
    price: 19.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_gluten-free-red-bean-brownie-with-peanut-butter-4456.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    name: 'Muffins de Chocolate',
    description: 'Muffins caseiros recheados com chips de chocolate',
    price: 14.90,
    category: 'Café da Manhã',
    imageUrl: '/kaboompics_homemade-chocolate-chip-muffins-1496.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    name: 'Rosquinhas Polonesas',
    description: 'Rosquinhas polonesas tradicionais com recheio de cereja e açúcar de confeiteiro',
    price: 17.90,
    category: 'Sobremesa',
    imageUrl: '/kaboompics_homemade-polish-doughnuts-with-cherry-filling-covered-with-powdered-sugar-traditional-speciality-on-fat-thursday-in-poland-11114.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    name: 'French Toast com Frutas Vermelhas',
    description: 'Rabanada francesa indulgente com banana, framboesas e blueberries',
    price: 29.90,
    category: 'Café da Manhã',
    imageUrl: '/kaboompics_indulgent-berry-banana-french-toast-feast-elegant-breakfast-with-raspberries-and-blueberries-33925.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    name: 'Pizza com Prosciutto',
    description: 'Pizza artesanal com prosciutto italiano e rúcula fresca',
    price: 42.90,
    category: 'Pizza',
    imageUrl: '/kaboompics_pizza-with-prosciutto-on-the-white-plate-8901.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '13',
    name: 'Tempura de Camarão',
    description: 'Camarões empanados crocantes com molho agridoce picante',
    price: 38.90,
    category: 'Asiático',
    imageUrl: '/kaboompics_prawns-tempura-with-sweet-chili-dip-ssaeu-kkanpunggi-7094.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '14',
    name: 'Salmão com Glaze de Bourbon',
    description: 'Filé de salmão grelhado com glaze especial de bourbon',
    price: 52.90,
    category: 'Principal',
    imageUrl: '/kaboompics_bourbon-glazed-salmon-2864.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '15',
    name: 'Pierogies Assados',
    description: 'Pierogies poloneses tradicionais assados com manteiga',
    price: 26.90,
    category: 'Principal',
    imageUrl: '/kaboompics_baked-pierogies-6279.jpg',
    available: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@example.com',
    phone: '(11) 98765-4321',
    role: 'customer',
    savedAddresses: [
      {
        street: 'Rua das Flores',
        number: '123',
        complement: 'Apto 45',
        neighborhood: 'Centro',
        city: 'São Paulo',
        state: 'SP',
        zipCode: '01234-567',
      },
    ],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Admin User',
    email: 'admin@pdiddy.com',
    phone: '(11) 99999-9999',
    role: 'admin',
    savedAddresses: [],
    createdAt: new Date('2024-01-01'),
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    userId: '1',
    items: [
      {
        productId: '1',
        product: mockProducts[0],
        quantity: 2,
        subtotal: 91.80,
      },
      {
        productId: '8',
        product: mockProducts[7],
        quantity: 2,
        subtotal: 11.80,
      },
    ],
    deliveryAddress: {
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Centro',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01234-567',
    },
    paymentMethod: {
      type: 'credit',
      cardNumber: '**** **** **** 1234',
      cardName: 'João Silva',
    },
    total: 103.60,
    status: 'delivered',
    createdAt: new Date('2024-01-15'),
  },
];

/**
 * Generate a unique ID
 */
export const generateId = (): string => {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
};
