openapi: 3.0.3
info:
  title: Tec Burger API
  version: 1.0.0
  description: API completa do Tec Burger - Catálogo de produtos e gestão de pedidos
servers:
  - url: http://localhost:8080
    description: API Gateway (Desenvolvimento)
  - url: https://api.example.com
    description: Produção
tags:
  - name: Products
    description: Operações de catálogo de produtos
  - name: Orders
    description: Operações de pedidos
security:
  - bearerAuth: []
paths:
  /api/catalog/api/v1/products:
    get:
      tags: [Products]
      summary: Listar produtos (paginação por cursor)
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: cursor
          schema:
            type: string
            nullable: true
        - in: query
          name: sort
          schema:
            type: string
            enum: [created_at_desc, created_at_asc]
            default: created_at_desc
      responses:
        '200':
          description: ok
          headers:
            X-Request-Id:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                required: [data, meta]
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  meta:
                    $ref: '#/components/schemas/PageMeta'
              examples:
                sample:
                  value:
                    data:
                      - id: "de305d54-75b4-431b-adb2-eb6b9e546014"
                        name: "Hambúrguer"
                        price: "25.90"
                        createdAt: "2025-11-10T22:00:00Z"
                        updatedAt: "2025-11-10T22:00:00Z"
                    meta:
                      nextCursor: "eyJpZCI6IiJ9"
    post:
      tags: [Products]
      summary: Criar produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, price]
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                price:
                  $ref: '#/components/schemas/Money'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '422':
          description: validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/catalog/api/v1/products/{productId}:
    get:
      tags: [Products]
      summary: Buscar produto por ID
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/order/api/v1/orders:
    get:
      tags: [Orders]
      summary: Listar pedidos (paginação por cursor)
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: cursor
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                required: [data, meta]
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  meta:
                    $ref: '#/components/schemas/PageMeta'
    post:
      tags: [Orders]
      summary: Criar pedido (assíncrono com idempotência)
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          description: Chave única para garantir idempotência (8-128 caracteres)
          schema:
            type: string
            minLength: 8
            maxLength: 128
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [productId, quantity]
              properties:
                productId:
                  type: string
                  format: uuid
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '202':
          description: Pedido aceito e será processado
          headers:
            Idempotency-Key:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                required: [orderId, status]
                properties:
                  orderId:
                    type: string
                    format: uuid
                  status:
                    $ref: '#/components/schemas/OrderStatus'
        '409':
          description: conflito (mesma chave, corpo diferente)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/order/api/v1/orders/{orderId}:
    get:
      tags: [Orders]
      summary: Buscar pedido por ID
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Money:
      type: string
      pattern: '^[0-9]+(\.[0-9]{2})$'
      example: "25.90"
      description: Valor monetário com 2 casas decimais
    Product:
      type: object
      required: [id, name, price, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 255
        price:
          $ref: '#/components/schemas/Money'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    OrderStatus:
      type: string
      enum: [pending, processing, completed, failed]
      description: Status do pedido
    Order:
      type: object
      required: [id, productId, quantity, unitPrice, status, createdAt, updatedAt]
      properties:
        id:
          type: string
          format: uuid
        productId:
          type: string
          format: uuid
        quantity:
          type: integer
          minimum: 1
        unitPrice:
          $ref: '#/components/schemas/Money'
        status:
          $ref: '#/components/schemas/OrderStatus'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PageMeta:
      type: object
      properties:
        nextCursor:
          type: string
          nullable: true
          description: Cursor para próxima página (null se não houver mais páginas)
    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: "not_found"
        message:
          type: string
        details:
          type: object
          additionalProperties: true